### ISSUE TITLE
Failure expiring backup

### ISSUE THREAD

**Issue by BrentWheeldon** [kjohnston/pgbackups-archive#52]
Hi there,

We recently upgraded to `1.0.2` and everything worked great, until we reached 30 backups when the `PgbackupsArchive::Job#expire` method kicks in. We're now getting `NoMethodError: undefined method 'backup_num' for #<Heroku::Command::Pg:0x007eff79f54900>` from `lib/pgbackups-archive/job.rb:69`. We're using heroku version `3.32.0`. Setting `PGBACKUPS_KEEP` to a larger number got things going again.

I'll dig into this more over the weekend/next week, but I thought I'd open this issue to see if anyone's seen it before.

Thanks!

**Comment by kjohnston** [comment]
@BrentWheeldon, thanks for reporting this.  I was able to reproduce it.  Looks like they're changing the `heroku` gem internals quite a bit, but they also seem to be auto-limiting the kept backups to 2, so I've released v1.0.3 which disables the expiration handling and mention of the PGBACKUPS_KEEP env var in the readme via #53.

v1.0.3 also sets the highest support version of the `heroku` gem to 3.32.x, since the API changes even more in 3.33+.
