### ISSUE TITLE
Could not find a valid gem 'heroku'

### ISSUE THREAD

**Issue by ebsaral** [kjohnston/pgbackups-archive#71]
I ran `gem install pgbackups-archive` but I am getting `ERROR:  Could not find a valid gem 'heroku' (<= 3.32, >= 3.28.6) in any repository` error.

**Comment by kjohnston** [comment]
It seems Heroku [has yanked](https://rubygems.org/gems/heroku/versions) all but the latest version of the deprecated `heroku` gem.  `pgbackups-archive` depends on some internals of the `heroku` gem that have since changed and that entire legacy CLI is now deprecated.  The time has come to move off of `pgbackups-archive`.  You might want to look at [heroku-database-backups](https://github.com/kbaum/heroku-database-backups) instead.  I'll update the readme.

**Comment by ebsaral** [comment]
Yeah I guessed the same. It's a shame. Thanks for replying.
